### ISSUE TITLE
高压力情况下与服务端建立连接失败出现程序异常

### ISSUE THREAD

**Issue by hjianhao** [btfak/sniper#3]
参见如下代码work.go：
//http & https
if config.Basic.https {
c.conn, err = tls.Dial("tcp", ip+":"+port, c.tlsConfig)
c.conn.SetDeadline(begin.Add(time.Second \* time.Duration(config.Ssl.timeout)))
} else {
c.conn, err = net.DialTCP("tcp", nil, c.tcpAddr)
c.conn.SetDeadline(begin.Add(time.Second \* time.Duration(config.Process.timeout)))
}

if err != nil {
c.trans.totalTime = 0
record.trans <- c.trans
c.conn.Close()
c.connect()
}

不应该直接调用SetDeadline，应该先处理err，因为如果net.DialTCP出错，此时conn应该是空对象，调用SetDeadline就会出问题。同理如果err != null，也不应该调用Close.

出现错误如下：

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e7f57]

goroutine 950 [running]:
runtime.panic(0x5ec660, 0x85b948)
   /usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
net.(*TCPConn).SetDeadline(0x0, 0xecb2c9b93, 0x3b1dc367, 0x860300, 0xecb2c9b93, ...)
   /usr/local/go/src/pkg/net/dial.go:1 +0x17

**Comment by btfak** [comment]
have fixed
