### ISSUE TITLE
postData.txt 格式是什么样的

### ISSUE THREAD

**Issue by gzw13999** [btfak/sniper#6]
username=name&password=123123  是这样吗？

还有要持久测试如何设置的？ 为何设置请求100万次执行一万次就结束了。

**Comment by sduqq2012** [comment]
同求，psotData是什么格式呢，怎么可以看请求的返回值呢，要不然怎么知道请求是否是正确的呢？

**Comment by btfak** [comment]
psotData可以是任何内容，就是http 的 body部分
